[package]
name = "substrate-api-client"
version = "0.1.0"
authors = ["Alain Brenzikofer <alain.brenzikofer@scs.ch>"]
edition = "2018"

[dependencies]
ws = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }
tiny-bip39 = "0.6.0"
substrate_bip39 = { package="substrate-bip39", git = "https://github.com/paritytech/substrate-bip39" }
rand = "0.6"
schnorrkel = "0.1"
hex = "0.3"
hex-literal = "0.1"
regex = "*"
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }
clap = { version = "2.33", features = ["yaml"] }
#twox-hash = "1.1.0"

primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate.git" }
node-primitives = { git = "https://github.com/paritytech/substrate.git" }
runtime_io = { package = "sr-io", git = "https://github.com/paritytech/substrate.git" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/paritytech/substrate.git", default-features = false }
inherents = { package = "substrate-inherents", git = "https://github.com/paritytech/substrate.git", default-features = false }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate.git" }
metadata = { package = "srml-metadata", git = "https://github.com/paritytech/substrate.git" }
balances = { package = "srml-balances", git = "https://github.com/paritytech/substrate.git" }
keyring = { package = "substrate-keyring", git = "https://github.com/paritytech/substrate.git" }
system = { package = "srml-system", git = "https://github.com/paritytech/substrate.git" }
#test_client = { package = "substrate-test-client", git = "https://github.com/paritytech/substrate.git" }

#node-runtime = { git = "https://github.com/paritytech/substrate.git" }
node-runtime = { package = "substratee-node-runtime", git = "https://github.com/scs/substraTEE-node.git" }

[features]
default = ["std"]
std = [
	"primitives/std",
	"parity-codec/std",
    "runtime_primitives/std",
	"node-runtime/std",
]